set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_CMAKE_SYSTEM_NAME Linux)
set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE ${CMAKE_CURRENT_LIST_DIR}/../toolchains/gcc-13-toolchain.cmake)

message("gcc-12 triplet CMAKE_C_COMPILER = ${CMAKE_C_COMPILER}")
message("gcc-12 triplet CMAKE_CXX_COMPILER = ${CMAKE_CXX_COMPILER}")

if(PORT MATCHES "ffmpeg")
    set(VCPKG_LIBRARY_LINKAGE dynamic)
endif()