name: ci
run-name: Continuous Integration ${{ github.actor }}
on:
  workflow_dispatch: # allow manual runs 
jobs:
  linux-clang:
    runs-on: ubuntu-22.04
    # runs-on: ubuntu-latest
    steps:
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1.9.0
      with:
        version: "16.0.4"
    - name: get cmake and ninja
      uses: lukka/get-cmake@v3.27.7
      with:
        cmakeVersion: 3.27.1  
        ninjaVersion: 1.11.1  
        useLocalCache: true         # <--= Use the local cache (default is 'false').
        useCloudCache: false        # <--= Ditch the cloud cache (default is 'true').
    - name: checkout code with LFS caching https://github.com/actions/checkout/issues/165
      uses: actions/checkout@v4
    - name: get vcpkg
      uses: lukka/run-vcpkg@v11.3
      with:
        vcpkgGitCommitId: '9f03078bdcbab3ad8c1e3927c40c3fb48e42501f'
         # This is the default location of the directory containing vcpkg sources.
         # Change it to the right location if needed.
         # vcpkgDirectory: '${{ github.workspace }}/vcpkg'
    - name: Run CMake consuming CMakePreset.json and run vcpkg to build packages
      uses: lukka/run-cmake@v10.7
      with:
        workflowPreset: 'clangr'