name: clang
run-name: Continuous Integration ${{ github.actor }}
on:
  workflow_dispatch: # allow manual runs 
jobs:
  linux-clang:
    runs-on: ubuntu-22.04
    steps:
    - name: print context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: clang info before
      run: |
        whereis clang++
        clang++ --version
        echo "Working Directory:"
        pwd
        ls -la
        echo "PATH:"
        echo $PATH
    - name: Print Working Directory and PATH before
      run: |
        echo "Working Directory:"
        pwd
        ls -la
        echo "PATH:"
        echo $PATH
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1.9.0
      with:
        version: "16.0.4"
    - name: Print Working Directory and PATH after
      run: |
        echo "Working Directory:"
        pwd
        ls -la
        echo "PATH:"
        echo $PATH
    - name: clang info after
      run: |
        whereis clang++
        clang++ --version
